/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as ThankYouSlugRouteImport } from './routes/thank-you.$slug'
import { Route as StatesStateRouteImport } from './routes/states.$state'
import { Route as ServicesCategoryRouteImport } from './routes/services.$category'
import { Route as PersonalRentersInsuranceRouteImport } from './routes/personal.renters-insurance'
import { Route as PersonalLandlordInsuranceRouteImport } from './routes/personal.landlord-insurance'
import { Route as PersonalHomeownersInsuranceRouteImport } from './routes/personal.homeowners-insurance'
import { Route as PersonalAutoInsuranceRouteImport } from './routes/personal.auto-insurance'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as FaqSlugRouteImport } from './routes/faq.$slug'
import { Route as BusinessInsuranceBondsRouteImport } from './routes/business-insurance.bonds'
import { Route as ServicesCategorySlugRouteImport } from './routes/services.$category.$slug'
import { Route as FaqHomeownersSlugRouteImport } from './routes/faq.homeowners.$slug'
import { Route as FaqBondsSlugRouteImport } from './routes/faq.bonds.$slug'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicDownloadsSlugRouteImport } from './routes/api/public/downloads.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FaqRoute,
} as any)
const ThankYouSlugRoute = ThankYouSlugRouteImport.update({
  id: '/thank-you/$slug',
  path: '/thank-you/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateRoute = StatesStateRouteImport.update({
  id: '/states/$state',
  path: '/states/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/services/$category',
  path: '/services/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRentersInsuranceRoute =
  PersonalRentersInsuranceRouteImport.update({
    id: '/personal/renters-insurance',
    path: '/personal/renters-insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const PersonalLandlordInsuranceRoute =
  PersonalLandlordInsuranceRouteImport.update({
    id: '/personal/landlord-insurance',
    path: '/personal/landlord-insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const PersonalHomeownersInsuranceRoute =
  PersonalHomeownersInsuranceRouteImport.update({
    id: '/personal/homeowners-insurance',
    path: '/personal/homeowners-insurance',
    getParentRoute: () => rootRouteImport,
  } as any)
const PersonalAutoInsuranceRoute = PersonalAutoInsuranceRouteImport.update({
  id: '/personal/auto-insurance',
  path: '/personal/auto-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqSlugRoute = FaqSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FaqRoute,
} as any)
const BusinessInsuranceBondsRoute = BusinessInsuranceBondsRouteImport.update({
  id: '/business-insurance/bonds',
  path: '/business-insurance/bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategorySlugRoute = ServicesCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesCategoryRoute,
} as any)
const FaqHomeownersSlugRoute = FaqHomeownersSlugRouteImport.update({
  id: '/homeowners/$slug',
  path: '/homeowners/$slug',
  getParentRoute: () => FaqRoute,
} as any)
const FaqBondsSlugRoute = FaqBondsSlugRouteImport.update({
  id: '/bonds/$slug',
  path: '/bonds/$slug',
  getParentRoute: () => FaqRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadsSlugRoute = ApiPublicDownloadsSlugRouteImport.update({
  id: '/api/public/downloads/$slug',
  path: '/api/public/downloads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business-insurance/bonds': typeof BusinessInsuranceBondsRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/personal/auto-insurance': typeof PersonalAutoInsuranceRoute
  '/personal/homeowners-insurance': typeof PersonalHomeownersInsuranceRoute
  '/personal/landlord-insurance': typeof PersonalLandlordInsuranceRoute
  '/personal/renters-insurance': typeof PersonalRentersInsuranceRoute
  '/services/$category': typeof ServicesCategoryRouteWithChildren
  '/states/$state': typeof StatesStateRoute
  '/thank-you/$slug': typeof ThankYouSlugRoute
  '/faq/': typeof FaqIndexRoute
  '/faq/bonds/$slug': typeof FaqBondsSlugRoute
  '/faq/homeowners/$slug': typeof FaqHomeownersSlugRoute
  '/services/$category/$slug': typeof ServicesCategorySlugRoute
  '/api/public/downloads/$slug': typeof ApiPublicDownloadsSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business-insurance/bonds': typeof BusinessInsuranceBondsRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/personal/auto-insurance': typeof PersonalAutoInsuranceRoute
  '/personal/homeowners-insurance': typeof PersonalHomeownersInsuranceRoute
  '/personal/landlord-insurance': typeof PersonalLandlordInsuranceRoute
  '/personal/renters-insurance': typeof PersonalRentersInsuranceRoute
  '/services/$category': typeof ServicesCategoryRouteWithChildren
  '/states/$state': typeof StatesStateRoute
  '/thank-you/$slug': typeof ThankYouSlugRoute
  '/faq': typeof FaqIndexRoute
  '/faq/bonds/$slug': typeof FaqBondsSlugRoute
  '/faq/homeowners/$slug': typeof FaqHomeownersSlugRoute
  '/services/$category/$slug': typeof ServicesCategorySlugRoute
  '/api/public/downloads/$slug': typeof ApiPublicDownloadsSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/business-insurance/bonds': typeof BusinessInsuranceBondsRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/personal/auto-insurance': typeof PersonalAutoInsuranceRoute
  '/personal/homeowners-insurance': typeof PersonalHomeownersInsuranceRoute
  '/personal/landlord-insurance': typeof PersonalLandlordInsuranceRoute
  '/personal/renters-insurance': typeof PersonalRentersInsuranceRoute
  '/services/$category': typeof ServicesCategoryRouteWithChildren
  '/states/$state': typeof StatesStateRoute
  '/thank-you/$slug': typeof ThankYouSlugRoute
  '/faq/': typeof FaqIndexRoute
  '/faq/bonds/$slug': typeof FaqBondsSlugRoute
  '/faq/homeowners/$slug': typeof FaqHomeownersSlugRoute
  '/services/$category/$slug': typeof ServicesCategorySlugRoute
  '/api/public/downloads/$slug': typeof ApiPublicDownloadsSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/faq'
    | '/sitemap.xml'
    | '/business-insurance/bonds'
    | '/faq/$slug'
    | '/offers/$slug'
    | '/personal/auto-insurance'
    | '/personal/homeowners-insurance'
    | '/personal/landlord-insurance'
    | '/personal/renters-insurance'
    | '/services/$category'
    | '/states/$state'
    | '/thank-you/$slug'
    | '/faq/'
    | '/faq/bonds/$slug'
    | '/faq/homeowners/$slug'
    | '/services/$category/$slug'
    | '/api/public/downloads/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/sitemap.xml'
    | '/business-insurance/bonds'
    | '/faq/$slug'
    | '/offers/$slug'
    | '/personal/auto-insurance'
    | '/personal/homeowners-insurance'
    | '/personal/landlord-insurance'
    | '/personal/renters-insurance'
    | '/services/$category'
    | '/states/$state'
    | '/thank-you/$slug'
    | '/faq'
    | '/faq/bonds/$slug'
    | '/faq/homeowners/$slug'
    | '/services/$category/$slug'
    | '/api/public/downloads/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/faq'
    | '/sitemap.xml'
    | '/business-insurance/bonds'
    | '/faq/$slug'
    | '/offers/$slug'
    | '/personal/auto-insurance'
    | '/personal/homeowners-insurance'
    | '/personal/landlord-insurance'
    | '/personal/renters-insurance'
    | '/services/$category'
    | '/states/$state'
    | '/thank-you/$slug'
    | '/faq/'
    | '/faq/bonds/$slug'
    | '/faq/homeowners/$slug'
    | '/services/$category/$slug'
    | '/api/public/downloads/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BusinessInsuranceBondsRoute: typeof BusinessInsuranceBondsRoute
  OffersSlugRoute: typeof OffersSlugRoute
  PersonalAutoInsuranceRoute: typeof PersonalAutoInsuranceRoute
  PersonalHomeownersInsuranceRoute: typeof PersonalHomeownersInsuranceRoute
  PersonalLandlordInsuranceRoute: typeof PersonalLandlordInsuranceRoute
  PersonalRentersInsuranceRoute: typeof PersonalRentersInsuranceRoute
  ServicesCategoryRoute: typeof ServicesCategoryRouteWithChildren
  StatesStateRoute: typeof StatesStateRoute
  ThankYouSlugRoute: typeof ThankYouSlugRoute
  ApiPublicDownloadsSlugRoute: typeof ApiPublicDownloadsSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof FaqRoute
    }
    '/thank-you/$slug': {
      id: '/thank-you/$slug'
      path: '/thank-you/$slug'
      fullPath: '/thank-you/$slug'
      preLoaderRoute: typeof ThankYouSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$state': {
      id: '/states/$state'
      path: '/states/$state'
      fullPath: '/states/$state'
      preLoaderRoute: typeof StatesStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/services/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/renters-insurance': {
      id: '/personal/renters-insurance'
      path: '/personal/renters-insurance'
      fullPath: '/personal/renters-insurance'
      preLoaderRoute: typeof PersonalRentersInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/landlord-insurance': {
      id: '/personal/landlord-insurance'
      path: '/personal/landlord-insurance'
      fullPath: '/personal/landlord-insurance'
      preLoaderRoute: typeof PersonalLandlordInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/homeowners-insurance': {
      id: '/personal/homeowners-insurance'
      path: '/personal/homeowners-insurance'
      fullPath: '/personal/homeowners-insurance'
      preLoaderRoute: typeof PersonalHomeownersInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/auto-insurance': {
      id: '/personal/auto-insurance'
      path: '/personal/auto-insurance'
      fullPath: '/personal/auto-insurance'
      preLoaderRoute: typeof PersonalAutoInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$slug': {
      id: '/faq/$slug'
      path: '/$slug'
      fullPath: '/faq/$slug'
      preLoaderRoute: typeof FaqSlugRouteImport
      parentRoute: typeof FaqRoute
    }
    '/business-insurance/bonds': {
      id: '/business-insurance/bonds'
      path: '/business-insurance/bonds'
      fullPath: '/business-insurance/bonds'
      preLoaderRoute: typeof BusinessInsuranceBondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category/$slug': {
      id: '/services/$category/$slug'
      path: '/$slug'
      fullPath: '/services/$category/$slug'
      preLoaderRoute: typeof ServicesCategorySlugRouteImport
      parentRoute: typeof ServicesCategoryRoute
    }
    '/faq/homeowners/$slug': {
      id: '/faq/homeowners/$slug'
      path: '/homeowners/$slug'
      fullPath: '/faq/homeowners/$slug'
      preLoaderRoute: typeof FaqHomeownersSlugRouteImport
      parentRoute: typeof FaqRoute
    }
    '/faq/bonds/$slug': {
      id: '/faq/bonds/$slug'
      path: '/bonds/$slug'
      fullPath: '/faq/bonds/$slug'
      preLoaderRoute: typeof FaqBondsSlugRouteImport
      parentRoute: typeof FaqRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/downloads/$slug': {
      id: '/api/public/downloads/$slug'
      path: '/api/public/downloads/$slug'
      fullPath: '/api/public/downloads/$slug'
      preLoaderRoute: typeof ApiPublicDownloadsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FaqRouteChildren {
  FaqSlugRoute: typeof FaqSlugRoute
  FaqIndexRoute: typeof FaqIndexRoute
  FaqBondsSlugRoute: typeof FaqBondsSlugRoute
  FaqHomeownersSlugRoute: typeof FaqHomeownersSlugRoute
}

const FaqRouteChildren: FaqRouteChildren = {
  FaqSlugRoute: FaqSlugRoute,
  FaqIndexRoute: FaqIndexRoute,
  FaqBondsSlugRoute: FaqBondsSlugRoute,
  FaqHomeownersSlugRoute: FaqHomeownersSlugRoute,
}

const FaqRouteWithChildren = FaqRoute._addFileChildren(FaqRouteChildren)

interface ServicesCategoryRouteChildren {
  ServicesCategorySlugRoute: typeof ServicesCategorySlugRoute
}

const ServicesCategoryRouteChildren: ServicesCategoryRouteChildren = {
  ServicesCategorySlugRoute: ServicesCategorySlugRoute,
}

const ServicesCategoryRouteWithChildren =
  ServicesCategoryRoute._addFileChildren(ServicesCategoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BusinessInsuranceBondsRoute: BusinessInsuranceBondsRoute,
  OffersSlugRoute: OffersSlugRoute,
  PersonalAutoInsuranceRoute: PersonalAutoInsuranceRoute,
  PersonalHomeownersInsuranceRoute: PersonalHomeownersInsuranceRoute,
  PersonalLandlordInsuranceRoute: PersonalLandlordInsuranceRoute,
  PersonalRentersInsuranceRoute: PersonalRentersInsuranceRoute,
  ServicesCategoryRoute: ServicesCategoryRouteWithChildren,
  StatesStateRoute: StatesStateRoute,
  ThankYouSlugRoute: ThankYouSlugRoute,
  ApiPublicDownloadsSlugRoute: ApiPublicDownloadsSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
